### ISSUE TITLE
Please create a tag of current master-branch

### ISSUE THREAD

**Issue by soda-2005** [camcima/camcima-soap-client#14]
Hi,
we want to use your PHP-library in one of our projects. The latest tag (1.1.0) is from 2016. Please, can you create a tag of the current master-branch (so, that we can use a tag, which contains the current/up-to-date code)?

Thanks a lot,
Jürgen Kußmann

**Comment by larsnovikov** [comment]
Hi, now you can add `
{
      "url": "https://github.com/camcima/camcima-soap-client.git",
      "type": "git"
}
` in 'repositories' section and `"camcima/camcima-soap-client": "dev-master"` in 'require' section in your composer.json
